-- Schema checkpoint after migrations 001-005, captured 2026-09-08.
-- For EMPTY Supabase databases only. No user data or credentials.
-- Apply this checkpoint instead of 001-005, then all timestamped migrations.
-- auth.users and Supabase roles/functions must already exist.
begin;

create table public."stripe_sessions" (
  "id" bigint generated by default as identity not null,
  "session_id" text not null,
  "user_id" uuid not null,
  "amount" bigint,
  "currency" text default 'usd'::text,
  "payment_status" text,
  "customer_email" text,
  "stripe_customer_id" text,
  "subscription_id" text,
  "price_id" text,
  "mode" text,
  "processed_at" timestamp with time zone default now(),
  "created_at" timestamp with time zone default now(),
  "expires_at" timestamp with time zone,
  "metadata" jsonb
);
create table public."user_plans" (
  "user_id" uuid not null,
  "plan" text default 'free'::text not null,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "stripe_customer_id" text,
  "stripe_subscription_id" text,
  "subscription_status" text default 'active'::text,
  "subscription_end_date" timestamp with time zone
);
create table public."user_usage" (
  "user_id" uuid not null,
  "resume_scans" integer default 0 not null,
  "cover_letters" integer default 0 not null,
  "job_matches" integer default 0 not null,
  "interview_preps" integer default 0 not null,
  "last_reset" timestamp with time zone default now(),
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "resume_tailors" integer default 0 not null
);
create table public."payment_history" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "event_type" text not null,
  "event_id" text,
  "amount" bigint not null,
  "currency" text default 'usd'::text,
  "status" text not null,
  "stripe_payment_intent_id" text,
  "stripe_charge_id" text,
  "stripe_invoice_id" text,
  "stripe_subscription_id" text,
  "description" text,
  "failure_reason" text,
  "metadata" jsonb,
  "created_at" timestamp with time zone default now(),
  "stripe_created_at" timestamp with time zone
);
create table public."job_applications" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "company" text not null,
  "role" text not null,
  "status" text default 'saved'::text not null,
  "url" text,
  "notes" text,
  "job_description" text,
  "applied_date" date,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
create table public."resume_versions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "name" text default 'Untitled Resume'::text not null,
  "content" text not null,
  "score" integer,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
create table public."keepalive" (
  "id" integer default 1 not null,
  "note" text default 'do not delete — keeps the project from auto-pausing on inactivity'::text not null,
  "created_at" timestamp with time zone default now() not null
);
alter table public."user_plans" add constraint "user_plans_plan_check" CHECK ((plan = ANY (ARRAY['free'::text, 'pro'::text])));
alter table public."user_usage" add constraint "user_usage_cover_letters_check" CHECK ((cover_letters >= 0));
alter table public."user_usage" add constraint "user_usage_interview_preps_check" CHECK ((interview_preps >= 0));
alter table public."user_usage" add constraint "user_usage_job_matches_check" CHECK ((job_matches >= 0));
alter table public."user_usage" add constraint "user_usage_resume_scans_check" CHECK ((resume_scans >= 0));
alter table public."payment_history" add constraint "payment_history_event_id_key" UNIQUE (event_id);
alter table public."payment_history" add constraint "payment_history_pkey" PRIMARY KEY (id);
alter table public."stripe_sessions" add constraint "stripe_sessions_pkey" PRIMARY KEY (id);
alter table public."stripe_sessions" add constraint "unique_session_id" UNIQUE (session_id);
alter table public."user_plans" add constraint "user_plans_pkey" PRIMARY KEY (user_id);
alter table public."user_usage" add constraint "user_usage_pkey" PRIMARY KEY (user_id);
alter table public."job_applications" add constraint "job_applications_status_check" CHECK ((status = ANY (ARRAY['saved'::text, 'applied'::text, 'interview'::text, 'offer'::text, 'rejected'::text])));
alter table public."job_applications" add constraint "job_applications_pkey" PRIMARY KEY (id);
alter table public."resume_versions" add constraint "resume_versions_score_check" CHECK (((score >= 0) AND (score <= 100)));
alter table public."resume_versions" add constraint "resume_versions_pkey" PRIMARY KEY (id);
alter table public."keepalive" add constraint "keepalive_id_check" CHECK ((id = 1));
alter table public."keepalive" add constraint "keepalive_pkey" PRIMARY KEY (id);
alter table public."payment_history" add constraint "payment_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."stripe_sessions" add constraint "stripe_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."user_plans" add constraint "user_plans_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."user_usage" add constraint "user_usage_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."job_applications" add constraint "job_applications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."resume_versions" add constraint "resume_versions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.user_plans (user_id, plan)
    values (new.id, 'free')
    on conflict (user_id) do nothing;
  insert into public.user_usage (user_id, resume_scans, cover_letters, job_matches, interview_preps, resume_tailors)
    values (new.id, 0, 0, 0, 0, 0)
    on conflict (user_id) do nothing;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_usage_summary()
 RETURNS TABLE(user_id uuid, plan text, is_pro boolean, resume_scans integer, cover_letters integer, job_matches integer, interview_preps integer, last_reset timestamp with time zone, days_since_reset numeric, usage_status text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    RETURN QUERY
    SELECT up.user_id,
           COALESCE(up.plan, 'free') as plan,
           (COALESCE(up.plan, 'free') = 'pro') as is_pro,
           COALESCE(uu.resume_scans, 0) as resume_scans,
           COALESCE(uu.cover_letters, 0) as cover_letters,
           COALESCE(uu.job_matches, 0) as job_matches,
           COALESCE(uu.interview_preps, 0) as interview_preps,
           COALESCE(uu.last_reset, NOW()) as last_reset,
           EXTRACT(epoch FROM (NOW() - COALESCE(uu.last_reset, NOW()))) / 86400 as days_since_reset,
           CASE
             WHEN up.plan = 'pro' THEN 'Pro - Unlimited'
             WHEN up.plan = 'free' THEN
               CASE
                 WHEN (COALESCE(uu.resume_scans, 0) >= 3 OR
                       COALESCE(uu.cover_letters, 0) >= 2 OR
                       COALESCE(uu.job_matches, 0) >= 2) THEN 'Free - At Limit'
                 WHEN (COALESCE(uu.resume_scans, 0) >= 2 OR
                       COALESCE(uu.cover_letters, 0) >= 1 OR
                       COALESCE(uu.job_matches, 0) >= 1) THEN 'Free - Near Limit'
                 ELSE 'Free - Under Limit'
               END
             ELSE 'Unknown'
           END AS usage_status
    FROM user_plans up
    FULL OUTER JOIN user_usage uu ON up.user_id = uu.user_id
    WHERE (up.user_id = auth.uid() OR uu.user_id = auth.uid())
       OR auth.role() = 'service_role';
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_revenue_summary()
 RETURNS TABLE(month timestamp with time zone, unique_customers bigint, total_transactions bigint, revenue numeric, refunds numeric, failed_payments bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    IF auth.role() != 'service_role' THEN
        RAISE EXCEPTION 'Unauthorized';
    END IF;

    RETURN QUERY
    SELECT DATE_TRUNC('month', ph.created_at) as month,
           COUNT(DISTINCT ph.user_id) as unique_customers,
           COUNT(*) as total_transactions,
           SUM(CASE WHEN ph.status = 'succeeded' THEN ph.amount ELSE 0 END) as revenue,
           SUM(CASE WHEN ph.status = 'refunded' THEN ph.amount ELSE 0 END) as refunds,
           SUM(CASE WHEN ph.status = 'failed' THEN 1 ELSE 0 END)::BIGINT as failed_payments
    FROM payment_history ph
    GROUP BY DATE_TRUNC('month', ph.created_at)
    ORDER BY month DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.downgrade_user_to_free(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    UPDATE user_plans SET plan = 'free' WHERE user_id = p_user_id;

    UPDATE user_usage SET
        resume_scans = 0,
        cover_letters = 0,
        job_matches = 0,
        interview_preps = 0,
        last_reset = NOW()
    WHERE user_id = p_user_id;

    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_payment_summary(p_user_id uuid)
 RETURNS TABLE(total_paid bigint, last_payment_date timestamp with time zone, total_payments integer, active_subscription boolean, subscription_id text, customer_id text)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        COALESCE(SUM(ph.amount), 0)::BIGINT as total_paid,
        MAX(ph.created_at) as last_payment_date,
        COUNT(ph.id)::INTEGER as total_payments,
        EXISTS(
            SELECT 1 FROM user_plans
            WHERE user_id = p_user_id
            AND plan = 'pro'
            AND subscription_status = 'active'
        ) as active_subscription,
        up.stripe_subscription_id as subscription_id,
        up.stripe_customer_id as customer_id
    FROM payment_history ph
    LEFT JOIN user_plans up ON up.user_id = ph.user_id
    WHERE ph.user_id = p_user_id
    AND ph.status = 'succeeded'
    GROUP BY up.stripe_subscription_id, up.stripe_customer_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_payments(p_user_id uuid, p_limit integer DEFAULT 10)
 RETURNS TABLE(payment_date timestamp with time zone, amount bigint, currency text, status text, description text, event_type text)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        ph.created_at as payment_date,
        ph.amount,
        ph.currency,
        ph.status,
        ph.description,
        ph.event_type
    FROM payment_history ph
    WHERE ph.user_id = p_user_id
    ORDER BY ph.created_at DESC
    LIMIT p_limit;
END;
$function$;

CREATE OR REPLACE FUNCTION public.initialize_user_data(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    INSERT INTO user_plans (user_id, plan)
    VALUES (p_user_id, 'free')
    ON CONFLICT (user_id) DO NOTHING;

    INSERT INTO user_usage (user_id, resume_scans, cover_letters, job_matches, interview_preps, last_reset)
    VALUES (p_user_id, 0, 0, 0, 0, NOW())
    ON CONFLICT (user_id) DO NOTHING;

    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_stripe_session(p_session_id text, p_user_id uuid, p_amount bigint DEFAULT NULL::bigint, p_currency text DEFAULT 'usd'::text, p_customer_email text DEFAULT NULL::text, p_stripe_customer_id text DEFAULT NULL::text, p_subscription_id text DEFAULT NULL::text, p_price_id text DEFAULT NULL::text, p_mode text DEFAULT 'subscription'::text, p_payment_status text DEFAULT 'unpaid'::text, p_metadata jsonb DEFAULT NULL::jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    INSERT INTO stripe_sessions (
        session_id, user_id, amount, currency, customer_email,
        stripe_customer_id, subscription_id, price_id, mode,
        payment_status, metadata
    )
    VALUES (
        p_session_id, p_user_id, p_amount, p_currency, p_customer_email,
        p_stripe_customer_id, p_subscription_id, p_price_id, p_mode,
        p_payment_status, p_metadata
    )
    ON CONFLICT (session_id)
    DO UPDATE SET
        payment_status = EXCLUDED.payment_status,
        subscription_id = COALESCE(EXCLUDED.subscription_id, stripe_sessions.subscription_id),
        stripe_customer_id = COALESCE(EXCLUDED.stripe_customer_id, stripe_sessions.stripe_customer_id),
        processed_at = NOW();

    RETURN FOUND;
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_stripe_session(p_session_id text, p_user_id uuid, p_metadata jsonb DEFAULT NULL::jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    INSERT INTO stripe_sessions (session_id, user_id, metadata)
    VALUES (p_session_id, p_user_id, p_metadata)
    ON CONFLICT (session_id) DO NOTHING;

    RETURN FOUND;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.upgrade_user_to_pro(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    PERFORM initialize_user_data(p_user_id);

    UPDATE user_plans SET plan = 'pro' WHERE user_id = p_user_id;

    UPDATE user_usage SET
        resume_scans = 0,
        cover_letters = 0,
        job_matches = 0,
        interview_preps = 0,
        last_reset = NOW()
    WHERE user_id = p_user_id;

    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.upgrade_user_to_pro_with_stripe(p_user_id uuid, p_stripe_customer_id text DEFAULT NULL::text, p_stripe_subscription_id text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    PERFORM initialize_user_data(p_user_id);

    UPDATE user_plans
    SET
        plan = 'pro',
        stripe_customer_id = COALESCE(p_stripe_customer_id, stripe_customer_id),
        stripe_subscription_id = COALESCE(p_stripe_subscription_id, stripe_subscription_id),
        subscription_status = 'active',
        updated_at = NOW()
    WHERE user_id = p_user_id;

    UPDATE user_usage SET
        resume_scans = 0,
        cover_letters = 0,
        job_matches = 0,
        interview_preps = 0,
        last_reset = NOW()
    WHERE user_id = p_user_id;

    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_plan_and_usage(p_user_id uuid)
 RETURNS TABLE(plan text, resume_scans integer, cover_letters integer, job_matches integer, interview_preps integer, last_reset timestamp with time zone)
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    PERFORM initialize_user_data(p_user_id);

    RETURN QUERY
    SELECT COALESCE(up.plan, 'free') as plan,
           COALESCE(uu.resume_scans, 0) as resume_scans,
           COALESCE(uu.cover_letters, 0) as cover_letters,
           COALESCE(uu.job_matches, 0) as job_matches,
           COALESCE(uu.interview_preps, 0) as interview_preps,
           COALESCE(uu.last_reset, NOW()) as last_reset
    FROM user_plans up
    LEFT JOIN user_usage uu ON up.user_id = uu.user_id
    WHERE up.user_id = p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.increment_usage(p_user_id uuid, p_feature text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    success BOOLEAN := FALSE;
    rows_affected INTEGER := 0;
BEGIN
    PERFORM initialize_user_data(p_user_id);

    CASE p_feature
      WHEN 'resume_scan' THEN
        UPDATE user_usage SET resume_scans = resume_scans + 1
        WHERE user_id = p_user_id;
        GET DIAGNOSTICS rows_affected = ROW_COUNT;

      WHEN 'cover_letter' THEN
        UPDATE user_usage SET cover_letters = cover_letters + 1
        WHERE user_id = p_user_id;
        GET DIAGNOSTICS rows_affected = ROW_COUNT;

      WHEN 'job_match' THEN
        UPDATE user_usage SET job_matches = job_matches + 1
        WHERE user_id = p_user_id;
        GET DIAGNOSTICS rows_affected = ROW_COUNT;

      WHEN 'interview_prep' THEN
        UPDATE user_usage SET interview_preps = interview_preps + 1
        WHERE user_id = p_user_id;
        GET DIAGNOSTICS rows_affected = ROW_COUNT;

      ELSE
        RETURN FALSE;
    END CASE;

    success := (rows_affected > 0);
    RETURN success;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_stripe_session_processed(p_session_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    RETURN EXISTS(SELECT 1 FROM stripe_sessions WHERE session_id = p_session_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.can_use_feature(p_user_id uuid, p_feature text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
    user_plan TEXT;
    current_usage INTEGER := 0;
    feature_limit INTEGER := 0;
    days_since_reset NUMERIC;
BEGIN
    PERFORM initialize_user_data(p_user_id);

    SELECT COALESCE(plan, 'free') INTO user_plan
    FROM user_plans
    WHERE user_id = p_user_id;

    IF user_plan = 'pro' THEN
        RETURN TRUE;
    END IF;

    SELECT EXTRACT(epoch FROM (NOW() - COALESCE(last_reset, NOW() - INTERVAL '31 days'))) / 86400
    INTO days_since_reset
    FROM user_usage
    WHERE user_id = p_user_id;

    IF days_since_reset >= 30 THEN
        UPDATE user_usage SET
            resume_scans = 0,
            cover_letters = 0,
            job_matches = 0,
            interview_preps = 0,
            last_reset = NOW()
        WHERE user_id = p_user_id;
    END IF;

    CASE p_feature
      WHEN 'resume_scan' THEN
        SELECT COALESCE(resume_scans, 0) INTO current_usage FROM user_usage WHERE user_id = p_user_id;
        feature_limit := 3;
      WHEN 'cover_letter' THEN
        SELECT COALESCE(cover_letters, 0) INTO current_usage FROM user_usage WHERE user_id = p_user_id;
        feature_limit := 2;
      WHEN 'job_match' THEN
        SELECT COALESCE(job_matches, 0) INTO current_usage FROM user_usage WHERE user_id = p_user_id;
        feature_limit := 2;
      WHEN 'interview_prep' THEN
        SELECT COALESCE(interview_preps, 0) INTO current_usage FROM user_usage WHERE user_id = p_user_id;
        feature_limit := 0;
      ELSE
        RETURN FALSE;
    END CASE;

    RETURN current_usage < feature_limit;
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_payment_event(p_user_id uuid, p_event_type text, p_event_id text, p_amount bigint, p_currency text DEFAULT 'usd'::text, p_status text DEFAULT 'succeeded'::text, p_stripe_payment_intent_id text DEFAULT NULL::text, p_stripe_charge_id text DEFAULT NULL::text, p_stripe_invoice_id text DEFAULT NULL::text, p_stripe_subscription_id text DEFAULT NULL::text, p_description text DEFAULT NULL::text, p_failure_reason text DEFAULT NULL::text, p_metadata jsonb DEFAULT NULL::jsonb, p_stripe_created_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
    INSERT INTO payment_history (
        user_id, event_type, event_id, amount, currency, status,
        stripe_payment_intent_id, stripe_charge_id, stripe_invoice_id,
        stripe_subscription_id, description, failure_reason,
        metadata, stripe_created_at
    )
    VALUES (
        p_user_id, p_event_type, p_event_id, p_amount, p_currency, p_status,
        p_stripe_payment_intent_id, p_stripe_charge_id, p_stripe_invoice_id,
        p_stripe_subscription_id, p_description, p_failure_reason,
        p_metadata, COALESCE(p_stripe_created_at, NOW())
    )
    ON CONFLICT (event_id) DO NOTHING;

    RETURN FOUND;
END;
$function$;

CREATE INDEX idx_stripe_sessions_created_at ON public.stripe_sessions USING btree (created_at DESC);
CREATE INDEX idx_stripe_sessions_session_id ON public.stripe_sessions USING btree (session_id);
CREATE INDEX idx_stripe_sessions_stripe_customer_id ON public.stripe_sessions USING btree (stripe_customer_id);
CREATE INDEX idx_stripe_sessions_subscription_id ON public.stripe_sessions USING btree (subscription_id);
CREATE INDEX idx_stripe_sessions_user_id ON public.stripe_sessions USING btree (user_id);
CREATE INDEX idx_user_plans_stripe_customer_id ON public.user_plans USING btree (stripe_customer_id);
CREATE INDEX idx_user_plans_stripe_subscription_id ON public.user_plans USING btree (stripe_subscription_id);
CREATE INDEX idx_user_plans_user_id ON public.user_plans USING btree (user_id);
CREATE INDEX idx_user_usage_last_reset ON public.user_usage USING btree (last_reset);
CREATE INDEX idx_user_usage_user_id ON public.user_usage USING btree (user_id);
CREATE INDEX idx_payment_history_created_at ON public.payment_history USING btree (created_at DESC);
CREATE INDEX idx_payment_history_event_id ON public.payment_history USING btree (event_id);
CREATE INDEX idx_payment_history_stripe_subscription_id ON public.payment_history USING btree (stripe_subscription_id);
CREATE INDEX idx_payment_history_user_id ON public.payment_history USING btree (user_id);
CREATE INDEX job_applications_user_id_idx ON public.job_applications USING btree (user_id);
CREATE INDEX resume_versions_user_id_idx ON public.resume_versions USING btree (user_id);
CREATE TRIGGER update_user_plans_updated_at BEFORE UPDATE ON public.user_plans FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_usage_updated_at BEFORE UPDATE ON public.user_usage FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER job_applications_updated_at BEFORE UPDATE ON public.job_applications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER resume_versions_updated_at BEFORE UPDATE ON public.resume_versions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
alter table public."stripe_sessions" enable row level security;
alter table public."user_plans" enable row level security;
alter table public."user_usage" enable row level security;
alter table public."payment_history" enable row level security;
alter table public."job_applications" enable row level security;
alter table public."resume_versions" enable row level security;
alter table public."keepalive" enable row level security;
create policy "Service role only for stripe_sessions" on public."stripe_sessions" as PERMISSIVE for ALL to "public" using ((auth.role() = 'service_role'::text)) with check ((auth.role() = 'service_role'::text));
create policy "Users can view own plan" on public."user_plans" as PERMISSIVE for SELECT to "public" using ((auth.uid() = user_id));
create policy "Users can view own usage" on public."user_usage" as PERMISSIVE for SELECT to "public" using ((auth.uid() = user_id));
create policy "Users can view own payments" on public."payment_history" as PERMISSIVE for SELECT to "public" using ((auth.uid() = user_id));
create policy "Users own their applications" on public."job_applications" as PERMISSIVE for ALL to "public" using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users own their resumes" on public."resume_versions" as PERMISSIVE for ALL to "public" using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Anyone can read keepalive" on public."keepalive" as PERMISSIVE for SELECT to "anon","authenticated" using (true);
grant INSERT on table public."stripe_sessions" to "anon";
grant SELECT on table public."stripe_sessions" to "anon";
grant UPDATE on table public."stripe_sessions" to "anon";
grant DELETE on table public."stripe_sessions" to "anon";
grant TRUNCATE on table public."stripe_sessions" to "anon";
grant REFERENCES on table public."stripe_sessions" to "anon";
grant TRIGGER on table public."stripe_sessions" to "anon";
grant INSERT on table public."stripe_sessions" to "authenticated";
grant SELECT on table public."stripe_sessions" to "authenticated";
grant UPDATE on table public."stripe_sessions" to "authenticated";
grant DELETE on table public."stripe_sessions" to "authenticated";
grant TRUNCATE on table public."stripe_sessions" to "authenticated";
grant REFERENCES on table public."stripe_sessions" to "authenticated";
grant TRIGGER on table public."stripe_sessions" to "authenticated";
grant INSERT on table public."stripe_sessions" to "service_role";
grant SELECT on table public."stripe_sessions" to "service_role";
grant UPDATE on table public."stripe_sessions" to "service_role";
grant DELETE on table public."stripe_sessions" to "service_role";
grant TRUNCATE on table public."stripe_sessions" to "service_role";
grant REFERENCES on table public."stripe_sessions" to "service_role";
grant TRIGGER on table public."stripe_sessions" to "service_role";
grant TRUNCATE on table public."user_plans" to "anon";
grant REFERENCES on table public."user_plans" to "anon";
grant TRIGGER on table public."user_plans" to "anon";
grant SELECT on table public."user_plans" to "authenticated";
grant TRUNCATE on table public."user_plans" to "authenticated";
grant REFERENCES on table public."user_plans" to "authenticated";
grant TRIGGER on table public."user_plans" to "authenticated";
grant INSERT on table public."user_plans" to "service_role";
grant SELECT on table public."user_plans" to "service_role";
grant UPDATE on table public."user_plans" to "service_role";
grant DELETE on table public."user_plans" to "service_role";
grant TRUNCATE on table public."user_plans" to "service_role";
grant REFERENCES on table public."user_plans" to "service_role";
grant TRIGGER on table public."user_plans" to "service_role";
grant TRUNCATE on table public."user_usage" to "anon";
grant REFERENCES on table public."user_usage" to "anon";
grant TRIGGER on table public."user_usage" to "anon";
grant SELECT on table public."user_usage" to "authenticated";
grant TRUNCATE on table public."user_usage" to "authenticated";
grant REFERENCES on table public."user_usage" to "authenticated";
grant TRIGGER on table public."user_usage" to "authenticated";
grant INSERT on table public."user_usage" to "service_role";
grant SELECT on table public."user_usage" to "service_role";
grant UPDATE on table public."user_usage" to "service_role";
grant DELETE on table public."user_usage" to "service_role";
grant TRUNCATE on table public."user_usage" to "service_role";
grant REFERENCES on table public."user_usage" to "service_role";
grant TRIGGER on table public."user_usage" to "service_role";
grant TRUNCATE on table public."payment_history" to "anon";
grant REFERENCES on table public."payment_history" to "anon";
grant TRIGGER on table public."payment_history" to "anon";
grant SELECT on table public."payment_history" to "authenticated";
grant TRUNCATE on table public."payment_history" to "authenticated";
grant REFERENCES on table public."payment_history" to "authenticated";
grant TRIGGER on table public."payment_history" to "authenticated";
grant INSERT on table public."payment_history" to "service_role";
grant SELECT on table public."payment_history" to "service_role";
grant UPDATE on table public."payment_history" to "service_role";
grant DELETE on table public."payment_history" to "service_role";
grant TRUNCATE on table public."payment_history" to "service_role";
grant REFERENCES on table public."payment_history" to "service_role";
grant TRIGGER on table public."payment_history" to "service_role";
grant INSERT on table public."job_applications" to "anon";
grant SELECT on table public."job_applications" to "anon";
grant UPDATE on table public."job_applications" to "anon";
grant DELETE on table public."job_applications" to "anon";
grant TRUNCATE on table public."job_applications" to "anon";
grant REFERENCES on table public."job_applications" to "anon";
grant TRIGGER on table public."job_applications" to "anon";
grant INSERT on table public."job_applications" to "authenticated";
grant SELECT on table public."job_applications" to "authenticated";
grant UPDATE on table public."job_applications" to "authenticated";
grant DELETE on table public."job_applications" to "authenticated";
grant TRUNCATE on table public."job_applications" to "authenticated";
grant REFERENCES on table public."job_applications" to "authenticated";
grant TRIGGER on table public."job_applications" to "authenticated";
grant INSERT on table public."job_applications" to "service_role";
grant SELECT on table public."job_applications" to "service_role";
grant UPDATE on table public."job_applications" to "service_role";
grant DELETE on table public."job_applications" to "service_role";
grant TRUNCATE on table public."job_applications" to "service_role";
grant REFERENCES on table public."job_applications" to "service_role";
grant TRIGGER on table public."job_applications" to "service_role";
grant INSERT on table public."resume_versions" to "anon";
grant SELECT on table public."resume_versions" to "anon";
grant UPDATE on table public."resume_versions" to "anon";
grant DELETE on table public."resume_versions" to "anon";
grant TRUNCATE on table public."resume_versions" to "anon";
grant REFERENCES on table public."resume_versions" to "anon";
grant TRIGGER on table public."resume_versions" to "anon";
grant INSERT on table public."resume_versions" to "authenticated";
grant SELECT on table public."resume_versions" to "authenticated";
grant UPDATE on table public."resume_versions" to "authenticated";
grant DELETE on table public."resume_versions" to "authenticated";
grant TRUNCATE on table public."resume_versions" to "authenticated";
grant REFERENCES on table public."resume_versions" to "authenticated";
grant TRIGGER on table public."resume_versions" to "authenticated";
grant INSERT on table public."resume_versions" to "service_role";
grant SELECT on table public."resume_versions" to "service_role";
grant UPDATE on table public."resume_versions" to "service_role";
grant DELETE on table public."resume_versions" to "service_role";
grant TRUNCATE on table public."resume_versions" to "service_role";
grant REFERENCES on table public."resume_versions" to "service_role";
grant TRIGGER on table public."resume_versions" to "service_role";
grant INSERT on table public."keepalive" to "anon";
grant SELECT on table public."keepalive" to "anon";
grant UPDATE on table public."keepalive" to "anon";
grant DELETE on table public."keepalive" to "anon";
grant TRUNCATE on table public."keepalive" to "anon";
grant REFERENCES on table public."keepalive" to "anon";
grant TRIGGER on table public."keepalive" to "anon";
grant INSERT on table public."keepalive" to "authenticated";
grant SELECT on table public."keepalive" to "authenticated";
grant UPDATE on table public."keepalive" to "authenticated";
grant DELETE on table public."keepalive" to "authenticated";
grant TRUNCATE on table public."keepalive" to "authenticated";
grant REFERENCES on table public."keepalive" to "authenticated";
grant TRIGGER on table public."keepalive" to "authenticated";
grant INSERT on table public."keepalive" to "service_role";
grant SELECT on table public."keepalive" to "service_role";
grant UPDATE on table public."keepalive" to "service_role";
grant DELETE on table public."keepalive" to "service_role";
grant TRUNCATE on table public."keepalive" to "service_role";
grant REFERENCES on table public."keepalive" to "service_role";
grant TRIGGER on table public."keepalive" to "service_role";
revoke all on function public.handle_new_user() from public, anon, authenticated, service_role;
grant execute on function public.handle_new_user() to service_role;
revoke all on function public.get_user_usage_summary() from public, anon, authenticated, service_role;
grant execute on function public.get_user_usage_summary() to service_role;
revoke all on function public.get_revenue_summary() from public, anon, authenticated, service_role;
grant execute on function public.get_revenue_summary() to service_role;
revoke all on function public.downgrade_user_to_free(uuid) from public, anon, authenticated, service_role;
grant execute on function public.downgrade_user_to_free(uuid) to anon;
grant execute on function public.downgrade_user_to_free(uuid) to authenticated;
grant execute on function public.downgrade_user_to_free(uuid) to service_role;
grant execute on function public.downgrade_user_to_free(uuid) to public;
revoke all on function public.get_user_payment_summary(uuid) from public, anon, authenticated, service_role;
grant execute on function public.get_user_payment_summary(uuid) to anon;
grant execute on function public.get_user_payment_summary(uuid) to authenticated;
grant execute on function public.get_user_payment_summary(uuid) to service_role;
grant execute on function public.get_user_payment_summary(uuid) to public;
revoke all on function public.get_user_payments(uuid,integer) from public, anon, authenticated, service_role;
grant execute on function public.get_user_payments(uuid,integer) to anon;
grant execute on function public.get_user_payments(uuid,integer) to authenticated;
grant execute on function public.get_user_payments(uuid,integer) to service_role;
grant execute on function public.get_user_payments(uuid,integer) to public;
revoke all on function public.initialize_user_data(uuid) from public, anon, authenticated, service_role;
grant execute on function public.initialize_user_data(uuid) to anon;
grant execute on function public.initialize_user_data(uuid) to authenticated;
grant execute on function public.initialize_user_data(uuid) to service_role;
grant execute on function public.initialize_user_data(uuid) to public;
revoke all on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) to anon;
grant execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) to authenticated;
grant execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) to service_role;
grant execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) to public;
revoke all on function public.record_stripe_session(text,uuid,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.record_stripe_session(text,uuid,jsonb) to anon;
grant execute on function public.record_stripe_session(text,uuid,jsonb) to authenticated;
grant execute on function public.record_stripe_session(text,uuid,jsonb) to service_role;
grant execute on function public.record_stripe_session(text,uuid,jsonb) to public;
revoke all on function public.set_updated_at() from public, anon, authenticated, service_role;
grant execute on function public.set_updated_at() to anon;
grant execute on function public.set_updated_at() to authenticated;
grant execute on function public.set_updated_at() to service_role;
grant execute on function public.set_updated_at() to public;
revoke all on function public.update_updated_at_column() from public, anon, authenticated, service_role;
grant execute on function public.update_updated_at_column() to anon;
grant execute on function public.update_updated_at_column() to authenticated;
grant execute on function public.update_updated_at_column() to service_role;
grant execute on function public.update_updated_at_column() to public;
revoke all on function public.upgrade_user_to_pro(uuid) from public, anon, authenticated, service_role;
grant execute on function public.upgrade_user_to_pro(uuid) to anon;
grant execute on function public.upgrade_user_to_pro(uuid) to authenticated;
grant execute on function public.upgrade_user_to_pro(uuid) to service_role;
grant execute on function public.upgrade_user_to_pro(uuid) to public;
revoke all on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) to anon;
grant execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) to authenticated;
grant execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) to service_role;
grant execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) to public;
revoke all on function public.get_user_plan_and_usage(uuid) from public, anon, authenticated, service_role;
grant execute on function public.get_user_plan_and_usage(uuid) to anon;
grant execute on function public.get_user_plan_and_usage(uuid) to authenticated;
grant execute on function public.get_user_plan_and_usage(uuid) to service_role;
grant execute on function public.get_user_plan_and_usage(uuid) to public;
revoke all on function public.increment_usage(uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.increment_usage(uuid,text) to anon;
grant execute on function public.increment_usage(uuid,text) to authenticated;
grant execute on function public.increment_usage(uuid,text) to service_role;
grant execute on function public.increment_usage(uuid,text) to public;
revoke all on function public.is_stripe_session_processed(text) from public, anon, authenticated, service_role;
grant execute on function public.is_stripe_session_processed(text) to anon;
grant execute on function public.is_stripe_session_processed(text) to authenticated;
grant execute on function public.is_stripe_session_processed(text) to service_role;
grant execute on function public.is_stripe_session_processed(text) to public;
revoke all on function public.can_use_feature(uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.can_use_feature(uuid,text) to anon;
grant execute on function public.can_use_feature(uuid,text) to authenticated;
grant execute on function public.can_use_feature(uuid,text) to service_role;
grant execute on function public.can_use_feature(uuid,text) to public;
revoke all on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) to anon;
grant execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) to authenticated;
grant execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) to service_role;
grant execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) to public;
grant usage on all sequences in schema public to service_role;
commit;
