
import type { Metadata } from "next";
import "./globals.css";
import DynamicNavbar from "./components/Navbar"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#212121] text-white min-h-screen antialiased">
        <DynamicNavbar />
        {children}
      </body>
    </html>
  );
}
