-- Only the server uses these legacy billing and usage functions.
-- Keep definitions for rollback compatibility, remove public API access.
revoke execute on function public.handle_new_user() from public, anon, authenticated;
grant execute on function public.handle_new_user() to service_role;
revoke execute on function public.get_user_usage_summary() from public, anon, authenticated;
grant execute on function public.get_user_usage_summary() to service_role;
revoke execute on function public.get_revenue_summary() from public, anon, authenticated;
grant execute on function public.get_revenue_summary() to service_role;
revoke execute on function public.downgrade_user_to_free(uuid) from public, anon, authenticated;
grant execute on function public.downgrade_user_to_free(uuid) to service_role;
revoke execute on function public.get_user_payment_summary(uuid) from public, anon, authenticated;
grant execute on function public.get_user_payment_summary(uuid) to service_role;
revoke execute on function public.get_user_payments(uuid,integer) from public, anon, authenticated;
grant execute on function public.get_user_payments(uuid,integer) to service_role;
revoke execute on function public.initialize_user_data(uuid) from public, anon, authenticated;
grant execute on function public.initialize_user_data(uuid) to service_role;
revoke execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.record_stripe_session(text,uuid,bigint,text,text,text,text,text,text,text,jsonb) to service_role;
revoke execute on function public.record_stripe_session(text,uuid,jsonb) from public, anon, authenticated;
grant execute on function public.record_stripe_session(text,uuid,jsonb) to service_role;
revoke execute on function public.set_updated_at() from public, anon, authenticated;
grant execute on function public.set_updated_at() to service_role;
revoke execute on function public.update_updated_at_column() from public, anon, authenticated;
grant execute on function public.update_updated_at_column() to service_role;
revoke execute on function public.upgrade_user_to_pro(uuid) from public, anon, authenticated;
grant execute on function public.upgrade_user_to_pro(uuid) to service_role;
revoke execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) from public, anon, authenticated;
grant execute on function public.upgrade_user_to_pro_with_stripe(uuid,text,text) to service_role;
revoke execute on function public.get_user_plan_and_usage(uuid) from public, anon, authenticated;
grant execute on function public.get_user_plan_and_usage(uuid) to service_role;
revoke execute on function public.increment_usage(uuid,text) from public, anon, authenticated;
grant execute on function public.increment_usage(uuid,text) to service_role;
revoke execute on function public.is_stripe_session_processed(text) from public, anon, authenticated;
grant execute on function public.is_stripe_session_processed(text) to service_role;
revoke execute on function public.can_use_feature(uuid,text) from public, anon, authenticated;
grant execute on function public.can_use_feature(uuid,text) to service_role;
revoke execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) from public, anon, authenticated;
grant execute on function public.record_payment_event(uuid,text,text,bigint,text,text,text,text,text,text,text,text,jsonb,timestamp with time zone) to service_role;
revoke all on public.stripe_sessions from anon, authenticated;
revoke all on public.keepalive from anon, authenticated;
revoke all on public.job_applications, public.resume_versions from anon;
